#pragma once

#include "../../os.log/include/public.h"
#include "../../glsl.composer/include/public.h"
#include "../../gl.platform/include/public.h"
#include "../../algorithms/include/public.h"
#include "../../tp.muparser/include/public.h"
#include "../../os.storage/include/public.h"
#include "../../model/include/public.h"
#include "../../wiremodeler/include/public.h"
#include "../../cg.math/include/public.h"
#include "../../sim.grid/include/public.h"
#include "../../gl.program/include/public.h"
#include "../../gl.text/include/public.h"
#include "../../os.audio/include/public.h"
#include "../../scene/include/public.h"
#include "../../llv/include/public.h"
#include "../../os.leap/include/public.h"
#include "../../os.video/include/public.h"
#include "../../gl.view/include/public.h"

#include "path.suite.h"
#include "path.manager.h"
